### PR TITLE
RPE-282: Smoke test

### PR DESCRIPTION
**Pull request by doncem**
### JIRA link (if applicable) ###

[Implement smoke tests for consumer](https://tools.hmcts.net/jira/browse/RPE-282)

### Change description ###

As per story requirement, implementing health point check for service to be running

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by nitinprabhu — APPROVED** [review]
👍

**Review by lgonczar — APPROVED** [review]
What would also be worth doing (not in this pull request) is including the queue, FTP and producer in the health check.

**Comment by doncem** [comment]
can add pdf service and the producer health check in here.

service bus and ftp is more involved and would actually check whether connected rather than health check

**Comment by doncem** [comment]
Ah. I'm thinking in functional test. Yep, must be different approach and actually including custom health check in the service itself, which combines all checks we want

**Pull request merged**
